In [93]:
import mne
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd
# Import the FOOOF object
from fooof import FOOOF
from fooof import FOOOFGroup
# Import a utility to download and load example data
from fooof.utils.download import load_fooof_data
from fooof.utils.params import compute_knee_frequency
from pathlib import Path
import glob
from math import floor
from scipy import stats
import math
import sys

sys.path.append("/home/b1044271/Columbia/Aperiodic_sleep/helpers/")
from utils import resample_stages

SyntaxError: expected ':' (utils.py, line 10)

In [50]:
cd 'Columbia/Results/Time-resolved/E257'

[Errno 2] No such file or directory: 'Columbia/Results/Time-resolved/E257'
/home/b1044271/Columbia/Results/Time-resolved/E257


In [51]:
ls

Knee_k.npy
Knee_k_20_2.npy
Offset_k_20_2.npy
Offset_nk_20_2.npy
Slope_k.npy
Slope_k_20_2.npy
Slope_nk.npy
Slope_nk_20_2.npy
Transitions/
VP01_notch2_ica_done.set_AllNight_Knee
VP01_notch2_ica_done.set_AllNight_NoKnee
VP03_notch2_ica_done.set_AllNight_Knee
VP03_notch2_ica_done.set_AllNight_NoKnee
VP04_notch2_ica_done.set_AllNight_Knee
VP04_notch2_ica_done.set_AllNight_NoKnee
VP05_notch2_ica_done.set_AllNight_Knee
VP05_notch2_ica_done.set_AllNight_NoKnee
VP06_notch2_ica_done.set_AllNight_Knee
VP06_notch2_ica_done.set_AllNight_NoKnee
VP07_notch2_ica_done.set_AllNight_Knee
VP07_notch2_ica_done.set_AllNight_NoKnee
VP08_notch2_ica_done.set_AllNight_Knee
VP08_notch2_ica_done.set_AllNight_NoKnee
VP10_notch2_ica_done.set_AllNight_Knee
VP10_notch2_ica_done.set_AllNight_NoKnee
VP11_notch2_ica_done.set_AllNight_Knee
VP11_notch2_ica_done.set_AllNight_NoKnee
VP12_notch2_ica_done.set_AllNight_Knee
VP12_notch2_ica_done.set_AllNight_NoKnee
VP13_notch2_ica_done.set_AllNight_Knee
VP13_notch2_ica_done.set

In [52]:
# get all FOOOF files
path_files = '/home/b1044271/Columbia/Results/Time-resolved/E257/*.npy'
aperiodic_files = glob.glob(path_files)

In [53]:
# get all FOOOF files
staging_files = '/home/b1044271/EEGsleep/SleepStaging/*.txt'
stage_files = glob.glob(staging_files)

In [124]:
sfiles = np.zeros([17,50000])*np.nan
i=0
for X in stage_files:
    x  = resample_stages(X, 2)
    sfiles[i,0:len(x)] = x
    i=i+1

In [156]:
aperiodic_files

['/home/b1044271/Columbia/Results/Time-resolved/E257/Slope_k.npy',
 '/home/b1044271/Columbia/Results/Time-resolved/E257/Slope_nk.npy',
 '/home/b1044271/Columbia/Results/Time-resolved/E257/r2_k.npy',
 '/home/b1044271/Columbia/Results/Time-resolved/E257/r2_nk.npy',
 '/home/b1044271/Columbia/Results/Time-resolved/E257/Knee_k.npy',
 '/home/b1044271/Columbia/Results/Time-resolved/E257/Slope_nk_20_2.npy',
 '/home/b1044271/Columbia/Results/Time-resolved/E257/Slope_k_20_2.npy',
 '/home/b1044271/Columbia/Results/Time-resolved/E257/r2_k_20_2.npy',
 '/home/b1044271/Columbia/Results/Time-resolved/E257/r2_nk_20_2.npy',
 '/home/b1044271/Columbia/Results/Time-resolved/E257/Knee_k_20_2.npy',
 '/home/b1044271/Columbia/Results/Time-resolved/E257/Offset_nk_20_2.npy',
 '/home/b1044271/Columbia/Results/Time-resolved/E257/Offset_k_20_2.npy']

In [193]:
t = 2 #time window we use for FOOOF
intrvl = 60 # length of the intercal we want to look at before and after transition point (in sec)
i = 0
for f in aperiodic_files:
    
    A = np.load(f)
    for x in np.arange(17):
        Stage = sfiles[x][~np.isnan(sfiles[x])]
        param = A[x]
        N2_o = [ii for ii in range(len(Stage)) if Stage.astype(int)[ii] == 2]
        N2_l = np.array(Stage)[np.array([iii + 1 for iii in N2_o[0:-2]])]
        N2_n1 = [iv for iv in range(len(N2_l)) if N2_l[iv] == 1]
        N2_n3 = [iv for iv in range(len(N2_l)) if N2_l[iv] == 3]
        
        N1t = [N2_o[idx] for idx in N2_n1]
        N3t = [N2_o[idx] for idx in N2_n3]
        
        for l in N1t:   
            N21 = param[l-(intrvl/t): l+(intrvl/t)]

        
        
        N23 = param[(np.array(N3t)-(intrvl/t)): (np.array(N3t)+(intrvl/t))]
        N21 = param[N1t-(intrvl/t): N1t+(intrvl/t)]
   
    

    
    
    
    
    
    

TypeError: only integer scalar arrays can be converted to a scalar index

In [195]:
np.array(N3t)-(intrvl/t)

array([ 1124.,  1904.,  2954.,  3119.,  3164.,  3329.,  3524.,  5579.,
        5654.,  5759.,  6749.,  6944.,  7784.,  9464.,  9569.,  9629.,
        9674., 11699.])

In [196]:
np.array(N3t)+(intrvl/t)


array([ 1184.,  1964.,  3014.,  3179.,  3224.,  3389.,  3584.,  5639.,
        5714.,  5819.,  6809.,  7004.,  7844.,  9524.,  9629.,  9689.,
        9734., 11759.])

# type(N2_o)

In [129]:
sfiles[x][~np.isnan(sfiles[x])]

array([0., 0., 0., ..., 0., 0., 0.])

In [94]:
np.arange(17)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [107]:
x

0

In [91]:
A1 = A[0][~np.isnan(A[0])]
sfiles1 = sfiles[0][~np.isnan(sfiles[0])]

In [92]:
len(sfiles1)

13875

In [73]:
def resample_stages(path_file, new_samp_rate):
    stage_file = pd.read_csv(path_file)
    #set required time resolution - stages are in 30 seconds so the conversion depends on the time resolution specified
    cov_eq = 30/new_samp_rate
    stages = list(stage_file.iloc[:,0])
    stages_n = [val for val in stages for _ in range(0, floor(cov_eq))]
    return(stages_n)

In [74]:
X =resample_stages(stage_files[i], 2)

In [76]:
stage_files[i]

'/home/b1044271/EEGsleep/SleepStaging/VP01.txt'